### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by inanahammad** [inanahammad/Cheat-Menu#1]
### Below is a list of issues that are found & need to be fixed,

- [ ] Fix ped spawn crash

### Below is a list of new features that are planned to be implemented,

- [ ]  Animation manager

- [ ] Camera focuses on the tuning piece when changing it.

- [ ]  Cloth changer

- [ ]  Object Spawner

- [ ]  Ped(mind) control
